id: IA0C53445
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-06-29T16:12:15.281740'
last_modified: '2022-06-29T16:12:15.281751'
parser: null
source_metadata:
  title: 'Śāntideva: Bodhicaryāvatāra'
  language: zh
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
